// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arikqpdylixqpqulxvqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyaWtxcGR5bGl4cXBxdWx4dnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTYzMDAsImV4cCI6MjA3MzY5MjMwMH0.YSocxSOF9c55kpn-kLCaBC_xnb5DH1SHqeHN3mZ8ivc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
